resources:
- repo: self
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- task: PackerBuild@1   
  inputs:
    templateType: 'custom'
    customTemplateLocation: '$(System.DefaultWorkingDirectory)/windows.json'
    customTemplateParameters: '{"client_id":"$(client_id)","client_secret":"$(client_secret)","tenant_id":"$(tenant_id)","subscription_id":"$(subscription_id)","managed_image_resource_group_name":"$(managed_image_resource_group_name)","managed_image_name":"$(managed_image_name)"}'
    imageUri: 'imageURL'
    imageId: 'imageResourceID'